/**
 * GitHub Integration Types
 */

export interface GitHubConfig {
  token: string;
  owner: string;
  repo: string;
  baseUrl?: string; // For GitHub Enterprise
}

export interface GitHubLabel {
  name: string;
  color: string;
  description?: string;
}

export interface GitHubMilestone {
  title: string;
  description?: string;
  dueOn?: string; // ISO date
  state?: 'open' | 'closed';
}

export interface GitHubIssue {
  title: string;
  body: string;
  labels?: string[];
  milestone?: number;
  assignees?: string[];
}

export interface GitHubPRTemplate {
  name: string;
  content: string;
}

export interface TaskBreakdown {
  title: string;
  description: string;
  priority: 'critical' | 'high' | 'medium' | 'low';
  category: string;
  estimatedHours?: number;
  dependencies?: string[];
  acceptanceCriteria?: string[];
}

export interface ReleasePhase {
  name: string;
  description: string;
  startDate?: string;
  endDate?: string;
  tasks: string[];
}

export interface ExportResult {
  success: boolean;
  created: {
    issues: number;
    milestones: number;
    labels: number;
    prTemplates: number;
  };
  errors: string[];
  urls: string[];
}

export interface ExportOptions {
  createLabels?: boolean;
  createMilestones?: boolean;
  createIssues?: boolean;
  createPRTemplates?: boolean;
  dryRun?: boolean;
  labelPrefix?: string;
}

// Document category to label mapping
export const CATEGORY_LABELS: Record<string, GitHubLabel> = {
  'Product & Strategy': {
    name: 'docs:product',
    color: '0052CC',
    description: 'Product and strategy documentation',
  },
  'Technical Architecture': {
    name: 'docs:architecture',
    color: '5319E7',
    description: 'Technical architecture documentation',
  },
  'User Experience': {
    name: 'docs:ux',
    color: 'D93F0B',
    description: 'User experience documentation',
  },
  'Development Workflow': {
    name: 'docs:dev',
    color: '0E8A16',
    description: 'Development workflow documentation',
  },
  'Quality Assurance': {
    name: 'docs:qa',
    color: 'FBCA04',
    description: 'Quality assurance documentation',
  },
};

// Priority to label mapping
export const PRIORITY_LABELS: Record<string, GitHubLabel> = {
  critical: {
    name: 'priority:critical',
    color: 'B60205',
    description: 'Critical priority - must be done immediately',
  },
  high: {
    name: 'priority:high',
    color: 'D93F0B',
    description: 'High priority - should be done soon',
  },
  medium: {
    name: 'priority:medium',
    color: 'FBCA04',
    description: 'Medium priority - normal importance',
  },
  low: {
    name: 'priority:low',
    color: 'C2E0C6',
    description: 'Low priority - can wait',
  },
};

// Standard labels for Blueprint
export const STANDARD_LABELS: GitHubLabel[] = [
  { name: 'blueprint', color: '7057FF', description: 'Generated by Intent Blueprint' },
  { name: 'documentation', color: '0075CA', description: 'Documentation related' },
  { name: 'task', color: '1D76DB', description: 'Implementation task' },
  { name: 'epic', color: '3E4B9E', description: 'Epic / large feature' },
  { name: 'spike', color: 'D4C5F9', description: 'Research / investigation' },
];
