/**
 * Document delivery via email or file upload
 */

import nodemailer from 'nodemailer';
import * as fs from 'fs';
import * as path from 'path';

export interface DeliveryOptions {
  smtp?: {
    host: string;
    port: number;
    secure?: boolean;
    auth: {
      user: string;
      pass: string;
    };
  };
  from?: string;
}

export interface EmailDeliveryResult {
  success: boolean;
  messageId?: string;
  error?: string;
}

export class DocDelivery {
  private transporter: nodemailer.Transporter | null = null;
  private from: string;

  constructor(options: DeliveryOptions = {}) {
    this.from = options.from || 'noreply@intentsolutions.io';

    if (options.smtp) {
      this.transporter = nodemailer.createTransport({
        host: options.smtp.host,
        port: options.smtp.port,
        secure: options.smtp.secure ?? options.smtp.port === 465,
        auth: options.smtp.auth,
      });
    }
  }

  async sendEmail(
    to: string,
    projectName: string,
    zipPath: string
  ): Promise<EmailDeliveryResult> {
    if (!this.transporter) {
      return {
        success: false,
        error: 'Email not configured. Set SMTP options to enable email delivery.',
      };
    }

    try {
      const info = await this.transporter.sendMail({
        from: this.from,
        to,
        subject: `Intent Blueprint Docs: ${projectName}`,
        text: `Your documentation for "${projectName}" is attached.\n\nGenerated by Intent Blueprint Docs\nhttps://github.com/intent-solutions-io/intent-blueprint-docs`,
        html: `
          <h2>Your Documentation is Ready!</h2>
          <p>Your documentation for <strong>${projectName}</strong> is attached as a ZIP file.</p>
          <p>Extract the ZIP to view all generated documents.</p>
          <hr>
          <p><small>Generated by <a href="https://github.com/intent-solutions-io/intent-blueprint-docs">Intent Blueprint Docs</a></small></p>
        `,
        attachments: [
          {
            filename: `${projectName.toLowerCase().replace(/[^a-z0-9]/g, '-')}-docs.zip`,
            path: zipPath,
          },
        ],
      });

      return {
        success: true,
        messageId: info.messageId,
      };
    } catch (error) {
      return {
        success: false,
        error: error instanceof Error ? error.message : 'Unknown error',
      };
    }
  }

  /**
   * Read zip file as buffer for direct upload to Slack/Discord
   */
  getZipBuffer(zipPath: string): Buffer {
    return fs.readFileSync(zipPath);
  }

  /**
   * Get file stats for display
   */
  getFileStats(zipPath: string): { size: string; files: number } {
    const stats = fs.statSync(zipPath);
    const sizeKB = Math.round(stats.size / 1024);
    const size = sizeKB > 1024 ? `${(sizeKB / 1024).toFixed(1)} MB` : `${sizeKB} KB`;

    return { size, files: 0 }; // File count would need to be passed in
  }
}
